### ISSUE TITLE
AttributeError: module 'quant' has no attribute 'quant_cuda'. Also got 'CUDA extension not installed.'

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [johnsmith0031/alpaca_lora_4bit#16]
(textgen) siddhesh@Revision-PC:~/alpaca_lora_4bit/text-generation-webui$ python server.py --gptq-bits 4 --gptq-model-type llama
*CUDA extension not installed.*

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/siddhesh/miniconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
Monkey Patch Completed.
Loading ../llama-7b-4bit.pt ...
Loading Model ...
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Loaded the model in 10.15 seconds.
../alpaca_lora_7b/ Lora Applied.
Apply auto switch and half
/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/modules/callbacks.py", line 65, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/modules/text_generation.py", line 215, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/peft/src/peft/peft_model.py", line 581, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 209, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/siddhesh/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/peft/src/peft/tuners/lora.py", line 682, in forward
    result = super().forward(x)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/GPTQ-for-LLaMa/autograd_4bit.py", line 160, in forward
    out = fast_4bit_forward(x, self.qweight, self.scales, self.zeros, self.bias)
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/GPTQ-for-LLaMa/autograd_4bit.py", line 115, in fast_4bit_forward
    output = matmul4bit(x, qweight, scales.float(), zeros.float())
  File "/home/siddhesh/alpaca_lora_4bit/text-generation-webui/../repository/GPTQ-for-LLaMa/autograd_4bit.py", line 37, in matmul4bit
    quant.quant_cuda.vecquant4matmul(x, qweight, y, scales, zeros)
AttributeError: module 'quant' has no attribute 'quant_cuda'

**Comment by johnsmith0031** [comment]
Did you have an error compiling the extension? Just found a bug in it and fixed. You can pull the new code and have another try.
