### ISSUE TITLE
AttributeError: module 'quant' has no attribute 'quant_cuda'

### ISSUE THREAD

**Issue by ehartford** [johnsmith0031/alpaca_lora_4bit#22]
Did I setup something wrong?
Thank you in advance. (I am so close, I saw it interacting with the GPU)

I was trying to run `python finetune.py`

```
/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
  0%|                                                                                                          | 0/62109 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/eric/git/alpaca_lora_4bit/finetune.py", line 138, in <module>
    trainer.train()
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/trainer.py", line 1911, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/trainer.py", line 2657, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/trainer.py", line 2689, in compute_loss
    outputs = model(**inputs)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/peft/src/peft/peft_model.py", line 529, in forward
    return self.base_model(
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/transformers/src/transformers/models/llama/modeling_llama.py", line 209, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/./repository/peft/src/peft/tuners/lora.py", line 682, in forward
    result = super().forward(x)
  File "/home/eric/git/alpaca_lora_4bit/./repository/GPTQ-for-LLaMa/autograd_4bit.py", line 159, in forward
    out = AutogradMatmul4bit.apply(x, self.qweight, self.scales, self.zeros)
  File "/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/eric/git/alpaca_lora_4bit/./repository/GPTQ-for-LLaMa/autograd_4bit.py", line 128, in forward
    quant.quant_cuda.vecquant4recons(qweight, buffer, scales, zeros)
AttributeError: module 'quant' has no attribute 'quant_cuda'
  0%|
```

**Comment by ehartford** [comment]
I see this line in quant.py

```
try:
    import quant_cuda
except:
    print('CUDA extension not installed.')
```

**Comment by Ph0rk0z** [comment]
Did you compile the kernel?

**Comment by ehartford** [comment]
This is originating from the install.sh script

```
FAILED: /home/eric/git/alpaca_lora_4bit/repository/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-310/quant_cuda.o
c++ -MMD -MF /home/eric/git/alpaca_lora_4bit/repository/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-310/quant_cuda.o.d -pthread -B /home/eric/miniconda3/envs/al4/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/eric/miniconda3/envs/al4/include -fPIC -O2 -isystem /home/eric/miniconda3/envs/al4/include -I/usr/local/cuda/include -fPIC -I/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include -I/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/TH -I/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/eric/miniconda3/envs/al4/include/python3.10 -c -c /home/eric/git/alpaca_lora_4bit/repository/GPTQ-for-LLaMa/quant_cuda.cpp -o /home/eric/git/alpaca_lora_4bit/repository/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-310/quant_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
In file included from /home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAGraphsC10Utils.h:3,
                 from /home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/c10/cuda/CUDACachingAllocator.h:4,
                 from /home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h:9,
                 from /home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAGuard.h:7,
                 from /home/eric/git/alpaca_lora_4bit/repository/GPTQ-for-LLaMa/quant_cuda.cpp:3:
/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
    6 | #include <cuda_runtime_api.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```

```
$ find / -name cuda_runtime_api.h 2>/dev/null
/home/eric/miniconda3/envs/gpt/lib/python3.10/site-packages/nvidia/cuda_runtime/include/cuda_runtime_api.h
/home/eric/miniconda3/envs/al/lib/python3.9/site-packages/nvidia/cuda_runtime/include/cuda_runtime_api.h
/usr/local/cuda-11.7/targets/x86_64-linux/include/cuda_runtime_api.h
```

**Comment by ehartford** [comment]
I am trying 

```
pip install nvidia-pyindex
pip install nvidia-cuda-runtime
```

**Comment by ehartford** [comment]
still install.sh fails

```
/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory
    6 | #include <cuda_runtime_api.h>
```

```
$ find / -name cuda_runtime_api.h 2>/dev/null
/home/eric/miniconda3/envs/gpt/lib/python3.10/site-packages/nvidia/cuda_runtime/include/cuda_runtime_api.h
/home/eric/miniconda3/envs/al4/lib/python3.10/site-packages/nvidia/cuda_runtime/include/cuda_runtime_api.h
/home/eric/miniconda3/envs/al/lib/python3.9/site-packages/nvidia/cuda_runtime/include/cuda_runtime_api.h
/usr/local/cuda-11.7/targets/x86_64-linux/include/cuda_runtime_api.h
```

**Comment by ehartford** [comment]
Figured it out.

`sudo ln -s /usr/local/cuda-11.7/include /usr/local/cuda/include`
