### ISSUE TITLE
AttributeError: module 'quant_cuda' has no attribute 'vecquant4recons'

### ISSUE THREAD

**Issue by ehartford** [johnsmith0031/alpaca_lora_4bit#32]
I got my 30b model trained, it took 40 hours
I got the monkey patch setup correctly
all the paths are happy
finally I have an error in my text-generation-webui logs

```
Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/modules/callbacks.py", line 63, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/modules/text_generation.py", line 218, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/peft/src/peft/peft_model.py", line 581, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/transformers/src/transformers/models/llama/modeling_llama.py", line 209, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/peft/src/peft/tuners/lora.py", line 682, in forward
    result = super().forward(x)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/GPTQ-for-LLaMa/autograd_4bit.py", line 162, in forward
    out = fast_4bit_forward(x, self.qweight, self.scales, self.zeros, self.bias)
  File "/home/eric/git/alpaca_lora_4bit/text-generation-webui/../repository/GPTQ-for-LLaMa/autograd_4bit.py", line 114, in fast_4bit_forward
    quant.quant_cuda.vecquant4recons(qweight, buffer, scales, zeros)
AttributeError: module 'quant_cuda' has no attribute 'vecquant4recons'
```

Any idea what could cause this?  I tried reinstalling quant_cuda and that didn't fix it.

It does seem to load the model correctly

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/eric/miniconda3/envs/textgen/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Monkey Patch Completed.
Loading ../llama-30b-4bit.pt ...
Loading Model ...
Loaded the model in 31.61 seconds.
../alpaca_lora/ Lora Applied.
Apply auto switch and half
/home/eric/miniconda3/envs/textgen/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860
```

![image](https://user-images.githubusercontent.com/1117701/228217590-b450d2d5-6e50-49a4-a1ae-c09f1dacc0c8.png)

**Comment by emosuka** [comment]
I've had this problem a bunch of times messing with different versions of GPTQ, Python, CUDA and more. All this quantized LLaMA stuff is experimental and unfinished, and very much a dependency nightmare. At least until maybe this stuff makes it into Transformers sometime, in a more finished state.

Anyway, the fact that it complains about vecquant4recons and not vecquant2matmul suggests you've got an older version of quant-cuda installed. You could also have multiple versions, with the wrong version taking priority somehow. They all show up as version 0.0.0 right now, so it can be hard to tell.

I would suggest `pip uninstall quant_cuda`, and running `python setyp.py install` from the repo downloaded by the installer. Make sure to delete the build directory inside that repo, to force a clean rebuild of the CUDA module. If that doesn't help, start over with a fresh conda environment maybe.

**Comment by ehartford** [comment]
I'll start again from scratch and see if it still happens

**Comment by ehartford** [comment]
Now I have a different error... closing this.
