### ISSUE TITLE
How to finetune 30B and can it be done with dual RTX 3090's?

### ISSUE THREAD

**Issue by juanps90** [johnsmith0031/alpaca_lora_4bit#50]
I am trying to finetune 30B but getting OOM. I was wondering if it's even possible with a single 24GiB card, and failing that I'd like to know if a second GPU would help.

**Comment by emosuka** [comment]
I don't know about dual GPU's, but a single 24 GB card can just barely run inference on the 30B model. Training takes considerably more memory.

Have you considered renting a server? RunPod has a 48GB A40 server for $0.74/hour at the moment, and 80 GB A100s usually cost around $2/hour. So you get a lot of hours of training time for the price of a 3090, especially if you factor in your own electricity costs.

**Comment by juanps90** [comment]
I haven't really looked into renting servers, but I will definitely check RunPod. Thank you!

**Comment by winglian** [comment]
Are you using gradient checkpointing? if not, that will greatly reduce the amount of VRAM required.

**Comment by juanps90** [comment]
I wasn't. Now I am passing --grad_chckpt. Let's see how it works! Thank you!

**Comment by juanps90** [comment]
It definitely worked! Thank you.

**Comment by nepeee** [comment]
I'm currently training a 13B one on 2x3090, it can do 2048 tokens * 64 batch size in 142sec and 74sec for 4x3090. The current code got OOM above 5x3090. Maybe its possible to train the 30B on 2 or more 3090 if you do model parallel like FSDP.

**Comment by alxfoster** [comment]
I was able to fine tune the 30B model using 2 3090's. Took 26 hours total.

**Comment by gururise** [comment]
> I was able to fine tune the 30B model using 2 3090's. Took 26 hours total.

What was the configuration you used to get things working on your 2x 3090's?

**Comment by alxfoster** [comment]
Sorry, it was 8 or 10 days ago and have tried so many configs that I don't remember exactly. I had used the https://github.com/tloen/alpaca-lora  > Checkpoint export (export_*_checkpoint.py)

... Now I'm struggling to figure out how to fine tune and merge the 65B-4bit with no luck so far.

**Comment by tensiondriven** [comment]
> I was able to fine tune the 30B model using 2 3090's. Took 26 hours total.

Could you please post the command line you used?  I'm struggling with a couple of errors and I'm not sure if it's my parameters or something else.

Not trying to hijack the thread, but here's my command line and my error, if anyone sees anything obviously wrong with it

```
python alpaca_lora_4bit/finetune.py \
  --ds_type txt \
  --lora_out_dir "$output_path" \
  --llama_q4_config_dir "$config_path" \
  --llama_q4_model "$model_path" \
  --mbatch_size 8 \
  --batch_size 2 \
  --epochs 3 \
  --lr 0.0002 \
  --cutoff_len 256 \
  --lora_r 8 \
  --lora_alpha 16 \
  --lora_dropout 0.05 \
  --val_set_size 0.2 \
  --warmup_steps 50 \
  --save_steps 50 \
  --save_total_limit 3 \
  --logging_steps 10 \
  --verbose \
  "$dataset_path"
```

Error:

```
Loaded the model in 8.14 seconds.
Fitting 4bit scales and zeros to half
Train Data: 0.00% outliers                                                                                                                                         
The following columns in the training set don't have a corresponding argument in `PeftModelForCausalLM.forward` and have been ignored: input. If input are not expected by `PeftModelForCausalLM.forward`,  you can safely ignore this message.
Traceback (most recent call last):
  File "/home/j/alpaca_lora_4bit/finetune.py", line 176, in <module>
    trainer.train()
  File "/home/j/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1661, in train
    return inner_training_loop(
  File "/home/j/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1684, in _inner_training_loop
    num_update_steps_per_epoch = len_dataloader // args.gradient_accumulation_steps
ZeroDivisionError: integer division or modulo by zero
```

**Comment by johnsmith0031** [comment]
batch_size should be at least mbatch_size. Will add an assert in repo.

**Comment by juanps90** [comment]
Just came to say that you can finetune 30b with dual rtx3090's.

Finetuning with full 2048 context size, running both cards at 22GiB each.

**Comment by tensiondriven** [comment]
I've successfully trained on 2x3090's now as well.  It seems that you can tune the parameters quite a bit, in terms of batch size etc based on your available VRAM.  

The bonus that I didn't realize until I did some training is that your power and heat requirements will be 1x3090 by virtue f how training is done - Only one card's gpu core will run at a time!  Pretty cool.

**Comment by tensiondriven** [comment]
Here's a slightly edited version of my crappy batch script if anyone finds it useful:

If anyone sees problems with the parameters I'm using, please do let me know!

```
model_size=$1
epochs=$2
dataset_path=$3
#config_path="./LLaMA-HF-4bit/llama-$model_size-4bit"
#model_path="./LLaMA-HF-4bit/llama-$model_size-4bit/llama-$model_size-4bit.safetensors"
output_path="./output"

config_path="/mnt/ml-metamind/ml/model-repos/gpt4-x-alpaca-30b-int4/"
model_path="/mnt/ml-metamind/ml/model-repos/gpt4-x-alpaca-30b-int4/gpt4-x-alpaca-30b-4bit.safetensors"

start_time=$(date +%Y%m%d-%H%M)

dataset_basename=`basename "$dataset_path" .txt`
cutoff_len=$4
lora_r=$5
lora_alpha=$6
micro_batch_size=$7
batch_size=$8

output_path="./output/$dataset_basename-$model_size-${epochs}e-${cutoff_len}co-${lora_r}r-${lora_alpha}a-${batch_size}b-$start_time"

set -e

stats_file="$output_path/run-info.yaml"
log_file="$output_path/run-info.log"

time \
python alpaca_lora_4bit/finetune.py \
  --ds_type txt \
  --lora_out_dir "$output_path" \
  --llama_q4_config_dir "$config_path" \
  --llama_q4_model "$model_path" \
  --mbatch_size $micro_batch_size  \
  --batch_size $batch_size \
  --epochs $epochs \
  --lr 0.0002 \
  --cutoff_len $cutoff_len \
  --lora_r $lora_r \
  --lora_alpha $lora_alpha \
  --lora_dropout 0.05 \
  --val_set_size 0.2 \
  --warmup_steps 100 \
  --logging_steps 100 \
  --verbose \
  --grad_chckpt \
  "$dataset_path" \
  | tee $log_file

  # --flash_attention
  # --xformers
  # --checkpoint
  # --grad_chckpt
  # --lora_dropout 0.05 \
  # --val_set_size 0.2 \
  # --warmup_steps 50 \
  # --save_steps 50 \
  # --save_total_limit 3 \
  # --logging_steps 10 \
  # --verbose \
  # --grad_chckpt \
  # --checkpoint \

echo "Copying to lora folder..."
rsync -r --progress $output_path /mnt/ml-metamind/ml/loras/

cat $stats_file
```
