### ISSUE TITLE
ModuleNotFoundError: No module named 'autograd_4bit'

### ISSUE THREAD

**Issue by FastBCSD** [johnsmith0031/alpaca_lora_4bit#54]

**Comment by FastBCSD** [comment]
>>> import peft

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/platform/anaconda3/envs/hcs did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.2/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/platform/huangchensen/llama_qunt/peft_main/src/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/home/platform/huangchensen/llama_qunt/peft_main/src/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/home/platform/huangchensen/llama_qunt/peft_main/src/peft/peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "/home/platform/huangchensen/llama_qunt/peft_main/src/peft/tuners/__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/platform/huangchensen/llama_qunt/peft_main/src/peft/tuners/lora.py", line 643, in <module>
    from autograd_4bit import Autograd4bitQuantLinear
ModuleNotFoundError: No module named 'autograd_4bit'

**Comment by FastBCSD** [comment]
>>> import peft

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/platform/anaconda3/envs/hcs did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.2/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda112.so...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/peft-0.3.0.dev0-py3.11.egg/peft/__init__.py", line 22, in <module>
  File "/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/peft-0.3.0.dev0-py3.11.egg/peft/mapping.py", line 16, in <module>
  File "/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/peft-0.3.0.dev0-py3.11.egg/peft/peft_model.py", line 31, in <module>
  File "/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/peft-0.3.0.dev0-py3.11.egg/peft/tuners/__init__.py", line 20, in <module>
  File "/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/peft-0.3.0.dev0-py3.11.egg/peft/tuners/lora.py", line 643, in <module>
  File "/home/platform/huangchensen/llama_qunt/autograd_4bit.py", line 6, in <module>
    from peft import PeftModel
ImportError: cannot import name 'PeftModel' from partially initialized module 'peft' (most likely due to a circular import) (/home/platform/anaconda3/envs/hcs/lib/python3.11/site-packages/peft-0.3.0.dev0-py3.11.egg/peft/__init__.py)

**Comment by s4rduk4r** [comment]
@FastBCSD it seems you haven't installed `cudatoolkit` package. Also I would recommend to use non-default conda environment

**Comment by johnsmith0031** [comment]
One of the solution is start your script from the path of this repo.
The other is add path of the repo in pythonpath which enables python to find the file.
```
import sys
sys.path.append(your path to alpaca_lora_4bit)
```

**Comment by FastBCSD** [comment]
thanks, the reason was found, I repeated the import of peft in autograd_4bit.py, and it was fine after deleting it
